name: "Release ROS Package"
description: |
  Create a ROS debian
author: "Gavin Suddrey"
branding:
  icon: "box"
  color: "gray-dark"
inputs:
  ros-distro:  # id of input
    description: 'ROS Distro Name (melodic,noetic,etc)'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
