#!/usr/bin/env python

import os
import re
import yaml

files = filter(lambda f: f.endswith('.deb'), os.listdir('target'))

packages = {}

for f in files:
  package_name = f[12:f.index('_')].replace('-', '_')  
  version = re.findall(r'[0-9]+\.[0-9]+\.[0-9]+', f)[0]

  if package_name not in packages:
    packages[package_name] = '0.0.0'

  if version > packages[package_name]:
    packages[package_name] = version

with open('versions.yml', 'w') as yaml_file:
    yaml.dump(packages, yaml_file, default_flow_style=False)
