#!/usr/bin/env python
from __future__ import print_function

import sys
import os
import yaml
import re

sources = sys.argv[1]
package = sys.argv[2]
ros_version = sys.argv[3]

version = 'ubuntu'

with open('/etc/os-release', 'r') as f:
	data = f.read()
	version = re.findall(r'^ID=(.*)', data, re.MULTILINE)[0]

apt_name = 'ros-{}-{}'.format(ros_version, package.replace('_', '-'))

with open(sources) as f:
	data = yaml.load(f, Loader=yaml.SafeLoader)

	if not data:
		data = {}

	if package not in data:
		data[package] = {}

	if version not in data[package]:
		data[package][version] = []

	if apt_name not in data[package][version]:
		data[package][version].append(apt_name)

with open(sources, 'w') as f:
	yaml.dump(data, f)
	print('Written update to', sources)


