#!/usr/bin/env python
import os
import sys
import yaml

path = os.path.dirname(os.path.realpath(__file__))

with open(os.path.join(path, 'versions.yml')) as f:
   data = yaml.load(f, Loader=yaml.BaseLoader)
   
   if sys.argv[1] not in data:
       data[sys.argv[1]] = '0.0.0'

   data[sys.argv[1]] = sys.argv[2]

with open(os.path.join(path, 'versions.yml'), 'w') as f:
   print(data)
   yaml.dump({str(key): str(data[key]) for key in data}, f, default_flow_style=False)
